name: Python CI workflow
#on:
#  push:
#    branches: main


jobs:

  build:
    runs-on: ubuntu-latest
    environment: DEV
    container:
      image: akdocker528/food_kart:latest
      credentials:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOKCER_PASSWORD}}
      volumes:
        - ${{github.workspace}}:/code

    steps:
      - name: echo workspace
        run: echo ${{ github.workspace }}

      - name: checkout
        uses: actions/checkout@v3
      
      - name:  echo workspace after  checkout
        run: echo ${{ github.workspace }}

      - name : install tree
        run: apt install tree

      - name : run python
        run: python -m tdd_food_kart_1  


