name: Python CI workflow
on:
  pull_request:
    branches: main
    types: [opened,reopened,synchronize]
  push:
    branches: main



jobs:

  build:
    runs-on: ubuntu-latest
    environment: DEV
    container:
      image: akdocker528/food_kart:latest
      credentials:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOKCER_PASSWORD}}
      volumes:
        - ${{github.workspace}}:/code

    steps:
      - name: echo workspace
        run: echo "${{ github.workspace }}"

      - name: echo event
        run: |
          echo "event name is:" ${{ github.event_name }}
          echo "event type is:" ${{ github.event.action }}

      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}

      
      - name:  echo workspace after  checkout
        run: echo ${{ github.workspace }}

      - name : install tree
        run: apt install tree

#      - name : list
#        run: tree .



