name: Python CI workflow
on:
  push:
    branches: main


jobs:

  build:
    runs-on: ubuntu-latest
    environment: DEV
#    steps:
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{secrets.DOCKER_USERNAME}}
#          password: ${{secrets.DOKCER_PASSWORD}}


    container:
      image: akdocker528/food_kart:latest
      credentials:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOKCER_PASSWORD}}

    steps:
      - name: echo workspace
        run: echo ${{ github.workspace }}

      - name: checkout
        uses: actions/checkout@v3
      
      - name:  echo workspace after  checkout
        run: echo ${{ github.workspace }}


